### PR TITLE
Example with functions for easier IO manipulation

### PR DESCRIPTION
**Pull request by AHugoson**
This script makes it easy to manage inputs and outputs.

What do you think about having this as a starting point for the tutorials? @MikelAyani @yaymalaga

### CODE REVIEW

**Comment by yaymalaga** [comment]
Looks good! If we want to make a tutorial for this driver we would need a helper for ease the individual bits manipulation

**Comment by AHugoson** [comment]
Yes, the easier the better :)
We could move most of the advanced stuff into methods of the ```Controller```, right?
The script we use in the tutorials could look something like:
``` python
import time
from Controller import UDP_Controller

if __name__ == '__main__':

    _controller = UDP_Controller()
    _controller.start()
    step_time = 1e-5
    inputs = [0, 0, 0, 0, 0, 0, 0, 0]
    outputs = [0, 0, 0, 0, 0, 0, 0, 0]

    while True:
        inputs = _controller.getInputs()

        # You can handle the inputs here, and manipulate the outputs
        # Example: connect out_0 directly to in_0
        outputs[0] = inputs[0]
        
        _controller.setOutputs(outputs)
        time.sleep(step_time)
```

**Comment by yaymalaga** [comment]
> We could move most of the advanced stuff into methods of the `Controller`, right?

Sure thing

**Comment by AHugoson** [comment]
We will leave this as is for now, the tutorial is customized after the existing example code.

**Pull request closed without merging**
